In [2]:
import numpy as np 

# Zero Dimensional Array 
arr = np.array(10)
# Single Dimensional Array
arr1 = np.array([1,2,3,4,5])

print(arr1[3])
print(arr1)




4
[1 2 3 4 5]


In [ ]:
print(arr1.dtype)

int64


In [ ]:
# create 2D Array 
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A.ndim)

2


In [6]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# print row,element and matrix
print(A[0]) # print row
print(A[2]) # print element
print(A) # print matrix

[1 2 3]
9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# iterate matrix

for i in A:
    for j in i:
        print(j,end=" ")
    print()


1 2 3 
4 5 6 
7 8 9 


In [13]:
# print rowwise addition
for i in A:
    sum=0 
    for j in i:
        print(j,end=" ")
        sum = sum+j
    print(sum)
    print()


1 2 3 6

4 5 6 15

7 8 9 24



In [18]:
# special numpy array 
print(np.zeros(5))
print(np.zeros((3,3)))
print(np.ones((2,3)))
print(np.full((2,2),8))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[8 8]
 [8 8]]


In [ ]:
new_array = np.random.random()
print(new_array)
new_array1 = np.random.randint(10,100,10)
print(new_array1)


0.6762850412639091
[91 99 58 94 85 43 43 44 73 72]


In [ ]:
B =np.array([23,45,56,78,90,33,12,10])
new_array2 = np.random.choice(B)
print(new_array2)
np.random.shuffle(B)
print(B)



12
[56 90 23 12 45 10 78 33]


In [ ]:
np.random.seed(2)#  #A seed is simply a starting point that NumPy uses to generate random numbers.
C = np.random.random()
print(C)

0.43599490214200376


In [ ]:
# create an array from arange method 

D = np.arange(10,50,2)
print(D)

# print Identity matrix
print(np.eye(3))


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# print shape and size
a =np.array([5,6,8,9])
b = np.array([[2,3,4],[5,6,7]])
print(a.shape)
print(b.shape)
print(a.size)
print(b.size)

(4,)
(2, 3)
4
6


In [78]:
# create 3D Array

threeD = np.array([[[1,2,3],[4,5,6]],[[10,11,12],[23,34,45]]])
print(threeD)
print(threeD[1])
print(threeD[0][0])
print(threeD[0][0][2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [23 34 45]]]
[[10 11 12]
 [23 34 45]]
[1 2 3]
3
