In [1]:
import numpy as np 
from sklearn.impute import KNNImputer

In [2]:
data = np.array([
    [2,4,np.nan],
    [5,1,6],
    [np.nan,5,7],
    [9,8,9]
])
print(data)

[[ 2.  4. nan]
 [ 5.  1.  6.]
 [nan  5.  7.]
 [ 9.  8.  9.]]


In [3]:
knn_imputer = KNNImputer(n_neighbors=2)
new_data = knn_imputer.fit_transform(data)
print(new_data)

[[2.  4.  6.5]
 [5.  1.  6. ]
 [5.5 5.  7. ]
 [9.  8.  9. ]]
