In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [2]:
# --------------------------------------------------
# Step 1: Create Dataset
# --------------------------------------------------

data = {
    "Math": [90, 80, 70, 60, 50],
    "Physics": [85, 75, 65, 55, 45],
    "Chemistry": [88, 78, 68, 58, 48],
    "Biology": [80, 70, 60, 50, 40],
    "English": [75, 65, 55, 45, 35]
}


In [3]:
df = pd.DataFrame(data)

print("Original Dataset:")
print(df)


Original Dataset:
   Math  Physics  Chemistry  Biology  English
0    90       85         88       80       75
1    80       75         78       70       65
2    70       65         68       60       55
3    60       55         58       50       45
4    50       45         48       40       35


In [4]:
# --------------------------------------------------
# Step 2: Check Dataset Shape
# --------------------------------------------------

print("\nOriginal Shape:")
print(df.shape)



Original Shape:
(5, 5)


In [5]:
# --------------------------------------------------
# Step 3: Standardize Data
# --------------------------------------------------

scaler = StandardScaler()

scaled_data = scaler.fit_transform(df)


print("\nStandardized Data:")
print(scaled_data)


Standardized Data:
[[ 1.41421356  1.41421356  1.41421356  1.41421356  1.41421356]
 [ 0.70710678  0.70710678  0.70710678  0.70710678  0.70710678]
 [ 0.          0.          0.          0.          0.        ]
 [-0.70710678 -0.70710678 -0.70710678 -0.70710678 -0.70710678]
 [-1.41421356 -1.41421356 -1.41421356 -1.41421356 -1.41421356]]


In [6]:
# --------------------------------------------------
# Step 4: Apply PCA
# Reduce 5 Features into 2 Features
# --------------------------------------------------

pca = PCA(n_components=2)


principal_components = pca.fit_transform(
    scaled_data
)


In [7]:
# --------------------------------------------------
# Step 5: Create PCA DataFrame
# --------------------------------------------------

pca_df = pd.DataFrame(
    principal_components,
    columns=[
        "Principal_Component_1",
        "Principal_Component_2"
    ]
)


In [8]:
print("\nAfter PCA Transformation:")
print(pca_df)


After PCA Transformation:
   Principal_Component_1  Principal_Component_2
0               3.162278           1.884111e-16
1               1.581139          -6.280370e-17
2              -0.000000           0.000000e+00
3              -1.581139           6.280370e-17
4              -3.162278           1.256074e-16


In [9]:
print("\nNew Shape After PCA:")
print(pca_df.shape)



New Shape After PCA:
(5, 2)


In [10]:
# --------------------------------------------------
# Step 7: Explained Variance Ratio
# --------------------------------------------------

variance = pca.explained_variance_ratio_


print("\nExplained Variance Ratio:")
print(variance)


print("\nTotal Information Retained:")
print(sum(variance) * 100, "%")


Explained Variance Ratio:
[1.00000000e+00 2.36658272e-33]

Total Information Retained:
100.0 %
