In [ ]:
import numpy as np 

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# columnwise addintion
print(np.sum(arr,axis=0))
# rowise addition
print(np.sum(arr,axis=1))


[12 15 18]
[ 6 15 24]


In [11]:
# Reshaping the array 
# convert 1D array into 2D array

arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

new_array = arr1.reshape(4,3)

print(new_array)

print("__________________")

# convert 1D array into 3D array 

new_array1 = arr1.reshape(3,2,2)

print(new_array1)









[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
__________________
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
oneD = arr.flatten()
print(oneD)

print(np.sum(arr)) # sum of all elements

[1 2 3 4 5 6 7 8 9]
45


In [24]:
A = np.array([12,23,45,56,67,78,90,100])
# seraching 
result = np.where(A==45)
print(result)
result1 = np.where(A==101)
print(result1)
print(np.where(A>50))

B = np.where(A>50)
for i in B:
    print(A[i])

(array([2]),)
(array([], dtype=int64),)
(array([3, 4, 5, 6, 7]),)
[ 56  67  78  90 100]


In [ ]:
# Statistical Method 

print(np.std(A))
print(np.var(A))
print(np.mean(A))
print(np.median(A))


29.105143445789782
847.109375
58.875
61.5


AttributeError: module 'numpy' has no attribute 'mode'

In [26]:
print(A*10)

[ 120  230  450  560  670  780  900 1000]


In [28]:
list1 = [12,23,45,56]

arr3 = np.array(list1)

print(arr3)

[12 23 45 56]


In [67]:
print(np.random.random()) # generate single float number
print(np.random.randint(10,100)) # generte single integer number
print(np.random.randint(10,100,5))

z = [23,34,55,66,77,88,99]
new_array = np.random.choice(z)
print(new_array)
np.random.shuffle(z)
print(z)

0.8927029150673554
45
[16 24 88 88 60]
66
[55, 23, 77, 99, 66, 88, 34]
